export type DetailService = {
  // id: number;
  // address: string;
  // price: number;
  // title: string;
  // rating: number;
  // description?: string;
  // urlImgCover: string;
  // urlOtherImg: string[];
  descripcion: string;
  fechaCreacion: string;
  id: string;
  imagenes: string[];
  direccion: string;
  precio: number;
  titulo: string;
  tipo: string;
  urlImagenPrincipal: string;
  usuarioPublicante: string;
};
